# Generated by Django 5.1.6 on 2025-03-14 04:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('fecha', models.DateField(auto_created=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='alertaDiagnostico',
            fields=[
                ('alerta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Alerta.alerta')),
                ('diagnostico', models.JSONField(blank=True, null=True)),
            ],
            bases=('Alerta.alerta',),
        ),
        migrations.CreateModel(
            name='alertaResultado',
            fields=[
                ('alerta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Alerta.alerta')),
                ('resultado', models.JSONField(blank=True, null=True)),
            ],
            bases=('Alerta.alerta',),
        ),
    ]
