# Generated by Django 5.1.7 on 2025-03-13 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Examen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='miRNA',
            fields=[
                ('examen_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Examen.examen')),
            ],
            bases=('Examen.examen',),
        ),
    ]
