# Generated by Django 5.2.1 on 2025-05-09 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examen', '0003_remove_examen_link_examen_archivo_examen_urlacceso'),
        ('Solicitud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='medico',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='examen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to='Examen.examen'),
        ),
    ]
