# Generated by Django 5.2.1 on 2025-05-09 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examen', '0002_rename_paciente_examen_paciente_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examen',
            name='link',
        ),
        migrations.AddField(
            model_name='examen',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='examenes/'),
        ),
        migrations.AddField(
            model_name='examen',
            name='urlAcceso',
            field=models.URLField(blank=True),
        ),
    ]
