# Generated by Django 5.1.6 on 2025-03-14 04:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examen', '0002_eeg_mirna_mri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
