# Generated by Django 4.2.20 on 2025-04-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('respuesta', models.TextField()),
                ('examen', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
