# Generated by Django 5.1.7 on 2025-03-14 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examen', '0004_remove_mirna_examen_ptr_remove_mri_examen_ptr_and_more'),
        ('Resultado', '0002_alter_resultado_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='examen',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Examen.examen'),
        ),
    ]
